name: "Kinding CI"
on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kindling_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Intall Postgres
        run: sudo apt install -yqq libpq-dev

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.1

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Gems
        run: |
          bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          rake db:create db:migrate

      - name: Compile assets
        run: ./bin/rails assets:precompile

      - name: Run tests
        run: bundle exec rspec

  # generate a workflow to auto merge if the above tests pass
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge pull request
        run: git merge ${{ github.event.pull_request.head.sha }}

      - name: Push changes
        run: git push

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
